### PR TITLE
set language for code example for syntax highlighting

### PR DESCRIPTION
**Pull request by marcuspoehls**

### CODE REVIEW

**Comment by marcuspoehls** [comment]
Hey John, any chance to get this merged? :blush:

**Comment by jeremylorino** [comment]
@marcuspoehls taking a look now

**Comment by jeremylorino** [comment]
@marcuspoehls will merge your PR in the am.

Thanks for the contrib!

**Comment by marcuspoehls** [comment]
Thank you 😊

**Pull request merged**
